"""empty message

Revision ID: 373505f64331
Revises: c8579613eb81
Create Date: 2026-04-13 22:24:47.045251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373505f64331'
down_revision = 'c8579613eb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
